project_id = "pohtomqnjpnuvuccorov"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-backup]
verify_jwt = false

[functions.process-stripe-payment]
verify_jwt = false

[functions.sync-stripe-sales]
verify_jwt = false

[functions.import-receitas-excel]
verify_jwt = true