project_id = "pohtomqnjpnuvuccorov"

[functions.stripe-webhook]
verify_jwt = false

[functions.auth-stripe-complete]
verify_jwt = false

[functions.api-checkout]
verify_jwt = false

[functions.create-backup]
verify_jwt = false
